### ISSUE TITLE
pexpect on windows missing spawn?

### ISSUE THREAD

**Issue by smithsp** [conda-forge/pexpect-feedstock#12]
My build of a [new recipe for`pIDLy`](https://github.com/conda-forge/staged-recipes/pull/4542) [failed on AppVeyor](https://ci.appveyor.com/project/conda-forge/staged-recipes/build/1.0.19161/job/xm3e3pptaf7wpif1#L421) with the error:
```
Traceback (most recent call last):
  File "C:\bld\pidly_1512764679000\test_tmp\run_test.py", line 2, in <module>
    import pidly
  File "C:\bld\pidly_1512764679000\_t_env\lib\site-packages\pidly.py", line 91, in <module>
    class IDL(pexpect.spawn):
AttributeError: 'module' object has no attribute 'spawn'
```
If this problem is not specific to the conda build of pexpect, then I can report it upstream to the pexpect developers.

**Comment by takluyver** [comment]
That's expected. From the docs:

> `pexpect.spawn` and `pexpect.run()` are *not* available on Windows, as they rely on Unix pseudoterminals (ptys). Cross platform code must not use these.

http://pexpect.readthedocs.io/en/stable/overview.html#pexpect-on-windows

**Comment by smithsp** [comment]
@takluyver Thank you for looking into this and responding.
