### ISSUE TITLE
Previous build broken

### ISSUE THREAD

**Issue by maresb** [conda-forge/pexpect-feedstock#26]
I think we need to [patch the repodata](https://github.com/conda-forge/conda-forge-repodata-patches-feedstock/tree/master/recipe) because [on Windows](https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=418867&view=logs&jobId=e5cdccbf-4751-5a24-7406-185c9d30d021&j=e5cdccbf-4751-5a24-7406-185c9d30d021&t=66e4a587-a723-53e9-873c-6c9a2c5971ea) I'm getting

```
(%PREFIX%) %SRC_DIR%>pip check 
pexpect 4.8.0 requires ptyprocess, which is not installed.
```

because for some reason it's using build 1 instead of build 2.

**Comment by maresb** [comment]
Context: in the latest build, the `# [not win]` selector was removed from `ptyprocess >=0.5`.

**Comment by ocefpaf** [comment]
:-( You are probably right. Do you want to send a PR to mark those as broken?

**Comment by maresb** [comment]
What's the advantage to marking as broken over submitting a repodata patch?

**Comment by ocefpaf** [comment]
> What's the advantage to marking as broken over submitting a repodata patch?

It is easier :smile: 

If you want to send a repodata patch please do!
